jessy/config/routes.rb
Ui::Application.routes.draw do

  devise_for :users

    root 'projects#index'

    resources :welcome 

    resource :activity do
    end

    resource :settings do
    end

    resources :projects do

        member do
            get 'last_successfull_build'
            get 'activity'
        end

        resources :builds do

            member do
                get     'changes'
                get     'list'
                get     'full_log'
                get     'jc_log'
                get     'cpanm_log'
                get     'configuration'
                get     'artefacts/*archive/', to: 'builds#download'
                post    'lock'
                post    'unlock'
                post    'release'
                post    'revert'
            end

            resources :shanpshots do
            end
    
        end
        
        resources :sources do
            member do
                post 'on'
                post 'off'
                post 'app'
            end
        end
    end
     

end

jessy/app/models/setting.rb
require 'erubis'

class Setting < ActiveRecord::Base

    def skip_missing_prerequisites_as_pinto_param
        if skip_missing_prerequisites.nil?
            ''
        else
            skip_missing_prerequisites.split(/\s+/).map { |i| "--skip-missing-prerequisite=#{i.chomp}"  }.join " "
        end
    end

    def pinto_repo_root
        ENV['PINTO_REPOSITORY_ROOT']
    end

    def pinto_config
        "#{pinto_repo_root}/.pinto/config/pinto.ini"
    end

    def pinto_config_erb
        "#{Rails.root}/templates/pinto.ini.erb"
    end

    def modulebuildrc
        "#{Rails.root}/public/.modulebuildrc"
    end

    def update_pinto_config
        template = File.read(pinto_config_erb)
        template = Erubis::Eruby.new(template)
        File.open( pinto_config, 'w') { |file| file.write( template.result(:settings => self )) }
    end

end

jessy/app/controllers/settings_controller.rb
class SettingsController < ApplicationController


    load_and_authorize_resource param_method: :settings_params

    def new
        Setting.new
    end

    def edit
        begin
        @settings = Setting.take!
        rescue ActiveRecord::RecordNotFound => ex
           @settings = Setting.new        
        end
    end

    def create

        @settings = Setting.new settings_params 
        if @settings.save
            @settings.update_pinto_config
            flash[:notice] = "settings have been successfully saved"
            redirect_to root_url
        else
            flash[:alert] = "error has been occured when save settings"
            render 'new'
        end
    end

    def update 

        @settings = Setting.take
    	params = settings_params
	    params.delete :jabber_password if params[:jabber_password].nil? or params[:jabber_password].empty?

        if @settings.update(params)
            @settings.update_pinto_config
            flash[:notice] = "settings have been successfully updated;"
            redirect_to root_url
        else
            flash[:alert] = "error has been occured when updating settings"
            render 'edit'
        end
    end


private

  def settings_params
      params.require(:setting).permit( 
            :perl5lib, 
            :skip_missing_prerequisites, 
            :pinto_downsteram_repositories, 
            :verbose,
            :jabber_host,
            :jabber_login,
            :jabber_password
     )
  end

end

jessy/app/helpers/settings_helper.rb
module SettingsHelper
end

jessy/app/views/settings/_form.html.erb
<%= form_for @settings, url: settings_path(@settings) do |f| %>
  <% if @settings.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@settings.errors.count, "error") %> prohibited
      this settings from being saved:</h2>
    <ul>
    <% @settings.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :perl5lib %><br>
    <%= f.text_field :perl5lib, :size => "100" %>
  </p>
  <p>
    <%= f.label :skip_missing_prerequisites %><br>
    <%= f.text_field :skip_missing_prerequisites, :size => "100" %>
  </p>
  <p>
    <%= f.label :pinto_downsteram_repositories %><br>
    <%= f.text_field :pinto_downsteram_repositories, :size => "100" %>
  </p>
  <p>
    <%= f.label :jc_timeout %><br>
    <%= f.text_field :jc_timeout, :size => "100" %>
  </p>
  <p>
    <%= f.label :jabber_host %><br>
    <%= f.text_field :jabber_host, :size => "50" %>
  </p>
  <p>
    <%= f.label :jabber_login %><br>
    <%= f.text_field :jabber_login, :size => "50" %>
  </p>
  <p>
    <%= f.label :jabber_password %><br>
    <%= f.password_field :jabber_password, :size => "50" %>
  </p>
    <%= f.submit %>

<% end %>

jessy/app/views/settings/edit.html.erb
<h2>Edit settings</h2>
<%= render 'form' %>