jessy/config/routes.rb
Ui::Application.routes.draw do

  devise_for :users

    root 'projects#index'

    resources :welcome 

    resource :activity do
    end

    resource :settings do
    end

    resources :projects do

        member do
            get 'last_successfull_build'
            get 'activity'
        end

        resources :builds do

            member do
                get     'changes'
                get     'list'
                get     'full_log'
                get     'jc_log'
                get     'cpanm_log'
                get     'configuration'
                get     'artefacts/*archive/', to: 'builds#download'
                post    'lock'
                post    'unlock'
                post    'release'
                post    'revert'
            end

            resources :shanpshots do
            end
    
        end
        
        resources :sources do
            member do
                post 'on'
                post 'off'
                post 'app'
            end
        end
    end
     

end

jessy/app/models/project.rb
class Project < ActiveRecord::Base

    has_many  :sources , :dependent => :destroy
    has_many :builds, :dependent => :destroy
    has_many :history, :dependent => :destroy

    validates :title, presence: true , length: { minimum: 2 }
    validates :jc_host, presence: true

    def jcc
        @jcc ||= JCC.new jc_host
    end

    def sources_ordered
        sources.sort { |x, y| ( y[:sn] <=> x[:sn] ) || (y[:id] <=> x[:id])  }
    end

    def sources_enabled
        sources_ordered.select { |s| s[:state] == true  }
    end

    def last_build
        builds.last
    end

    def has_builds?
        builds.size > 0
    end


    def last_successfull_build
        builds.select {|b| b.state == 'succeeded' and ! b.distribution_name.nil?  }.last
    end

    def url_for_build build
        "/projects/#{id}/builds/#{build.id}"
    end

    def has_last_successfull_build?
         last_successfull_build.nil? == false
    end

    def has_distribution_source?
        begin
            distribution_source
            true
        rescue ActiveRecord::RecordNotFound => ex
            false
        end
    end

    def distribution_source
        sources.find distribution_source_id
    end


    def distribution_indexed_url
        url = if has_distribution_source? == true
            distribution_source._indexed_url
        else
            nil
        end
    end

    def notify?
        notify == true
    end

    def verbose?
        verbose
    end


    def jc_hosts
        [
            {  :name => 'default : debian6 ( pinto.webdev.x:4000 )',  :url => 'http://pinto.webdev.x:4000' },
            {  :name => 'new: debian7 ( jc-wheezy.x:4000 )' , :url  => 'http://jc-wheezy.x:4000' },
            {  :name => 'test: debian6 ( pinto.webdev.x:4001 ) ',  :url => 'http://pinto.webdev.x:4001' }
        ]
    end
end

jessy/app/controllers/projects_controller.rb
require 'open3'

class ProjectsController < ApplicationController


    skip_before_filter :authenticate_user!, :only => [ :last_successfull_build ]

    load_and_authorize_resource param_method: :project_params

    def new
        @project = Project.new
    end

    def create
        # render text: params[:project].inspect
        @project = Project.new project_params 
        if @project.save
            flash[:notice] = "project # #{@project.id} has been successfully created"
            redirect_to @project
        else
            flash[:alert] = "error has been occured when creating project"
            render 'new'
        end
    end

    def update 
        @project = Project.find(params[:id])
        
        if @project.update(project_params)
            flash[:notice] = "project # #{@project.id} has been successfully updated"
            @project.history.create!( { :commiter => current_user.username, :action => "update project ID: #{@project.id}" })
            redirect_to [:edit, @project]
        else
            flash[:alert] = "error has been occured when updating project ID:#{@project.id} data"
            render 'edit'
        end
    end

    def edit 
        @project = Project.find(params[:id])
    end

    def show
        @project = Project.find(params[:id])
    end

    def index
        @projects = Project.all
    end

    def activity
        @project = Project.find(params[:id])
        @history = History.limit(50).order( id: :desc ).where(' project_id = ? ', @project.id )
    end


    def destroy 
        @project = Project.find(params[:id])

        if @project.has_builds?
            flash[:warn] = "project ID:#{@project.id} has builds, remove all projects builds first"
        else
            @project.destroy
            flash[:notice] = "project ID:#{@project.id} has been successfully removed"
        end
        redirect_to controller: 'projects'

    end

    def last_successfull_build
        @project = Project.find(params[:id])
        render text: root_url + 'projects/' + "#{@project.id}" + '/builds/' + "#{@project.last_successfull_build.id}" +  '/artefacts/' + @project.last_successfull_build.distribution_name
    end


private

  def project_params
      params.require(:project).permit( 
            :title, :text, :jc_host,
            :distribution_source_id,
            :notify, :verbose, :force_mode,
            :recipients
     )
  end

  def _execute_command(cmd, raise_ex = true)
    retval = false
    Open3.popen2e(cmd) do |stdin, stdout_err, wait_thr|
        while line = stdout_err.gets
            logger :debug, line
        end
        exit_status = wait_thr.value
        retval = exit_status.success?
        unless exit_status.success?
          raise "command #{cmd} failed" if raise_ex == true
       end
    end
    retval
 end

end

jessy/app/helpers/projects_helper.rb
module ProjectsHelper
end

jessy/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited
      this project from being saved:</h2>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => "100" %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :size => "102x5" %>
  </p>

  <% if @project.jc_host %>
  <p>
    <%= f.label :jc_host %><br>
    <%= f.text_field :jc_host, :size => "100", :disabled => true %>
  </p>
  <% else %>  
  <p>
    <%= f.label :jc_host %><br>
    <%= f.select(:jc_host, @project.jc_hosts.collect {|h| [ h[:name], h[:url] ] }, { prompt: 'Select JC Host'} ) %>
  </p>
  <% end %>

  <p>
     <%= f.check_box :verbose, { :value => true , :checked => @project[:verbose] } %>
     <%= f.label(:verbose, "verbose logging") %>
  </p>

  <p>
     <%= f.check_box :force_mode, { :value => true , :checked => @project[:force_mode] } %>
     <%= f.label(:force_mode, "forcefully reinstall sources, even no changes in SCM found") %>
  </p>

  <p>
    <%= f.check_box :notify, { :value => true , :checked => @project[:notify] } %>
    <%= f.label(:force_mode, "notify me when builds fail/success") %>
  </p>

  <p>
    <%= f.label :recipients %><br>
    <%= f.text_field :recipients, :size => "100" %>
  </p>


  <p>
    <%= f.submit %>
  </p>

 <% end %>

 <%- unless @project.sources_ordered.empty? %>

<h2> Change project components </h2>
	<table class="table-bordered table-striped table">   
	<tr>
		<th>Sort Number</th>
		<th>URL</th>
		<th>SCM Type</th>
		<th>Is Application Main Component ?</th>
		<th>Actions</th>
	</tr>
    <% @project.sources_ordered.each do |item| %>
      <tr>
        <td><%= item[:sn] %></td>
        <td><%= item._indexed_url  %></td>
        <td>[<%= item[:scm_type] %>]</td>
        <% if item.id == @project.distribution_source_id %>
            <td>true</td>
        <% else %>
            <td>false</td>
        <% end %> 
        <td>
        <% unless item.id == @project.distribution_source_id %>
            <%= link_to 'App', [ :app, item.project, item   ], method: :post,  title: "mark this source as an application source" %> |
        <% end %>
            <%= link_to 'Delete', [ item.project, item], method: :delete, title: "remove this source", data: { confirm: "You are about to delete source # #{item[:id]} in project #{@project[:id]}. Are you shure ?" }   %>
        </td>
      </tr>
    <% end %>
    </table>


[ <%= link_to "Change sources sort order",  edit_project_source_path( @project, @project.sources_ordered.first ) %> ]

<% end %>

jessy/app/views/projects/activity.html.erb
<strong>Project's Recent Activities</strong> |
    <%= link_to 'Back To Project', project_path(@project) %>
<pre>
  <strong>Project Title:</strong> <%= @project.title %>
  <strong>Project ID:</strong> <%= @project.id %>
</pre>

  <table class="table-bordered table-striped table">
  <tr>
    <th>Time</th>
    <th>Commiter</th>
    <th>Action</th>
  </tr>
  <% @history.each do |l| %>
  <tr>
    <td>
        <%= l[:created_at].strftime('%B %d, %Y at %H:%M')  %>
    </td>
    <td>
        <%= l[:commiter].nil? ? 'anonimous' : begin c = Resolv.new.getname(l[:commiter]) rescue l[:commiter] else c end   %>
    </td>
    <td>
        <%= l[:action] %>
    </td>
  </tr>
  <% end %>
  </table>

jessy/app/views/projects/destroy.html.erb
<h2><%= @message %></h2>

jessy/app/views/projects/edit.html.erb
<%= link_to 'Back To Project', project_path(@project) %> | <%= link_to 'Run New Build', url_for([@project, :builds]), method: :post  %>
<h2>Update Project Settings </h2>

<pre>
    ID : <%= @project[:id] %>
</pre>

<%= render 'form' %>

<h2>Add component to project</h2>
<%= form_for([@project, @project.sources.build]) do |f| %>
  <p>
    <%= f.label 'Scm Type' %><br>
    <%= f.select :scm_type, options_for_select(['svn', 'git' ]),  {}, :onChange=>"javascript: if (this.selectedIndex == 1) { \n this.form.source_git_tag.disabled = false; \n this.form.source_git_branch.disabled = false; \n this.form.source_git_folder.disabled = false; \n }; \n\n if (this.selectedIndex == 0 ) { \n this.form.source_git_tag.disabled = true; \n this.form.source_git_branch.disabled = true; \n this.form.source_git_folder.disabled = true; \n this.form.source_git_tag.value = ''; \n this.form.source_git_branch.value = ''; this.form.source_git_folder.value = ''; };  "  %><br>
    <%= f.label :git_branch %><br>
    <%= f.text_field :git_branch, :disabled => true %><br>
    <%= f.label :git_tag %><br>
    <%= f.text_field :git_tag, :disabled => true %><br>
    <%= f.label :git_folder %><br>
    <%= f.text_field :git_folder, :disabled => true %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url , :size => '100' %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

jessy/app/views/projects/index.html.erb
<hr>

<h1>Projects List</h1>
 
<table class="table-bordered table-striped table">
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Text</th>
    <th>Last Build</th>
    <th>Artefacts</th>
    <th>Builds Total / Builds Succeeded </th>
    <th>Actions</th>
  </tr>
 
  <% @projects.each do |item| %>
    <tr>
      <td><%= item[:id] %></td>
      <td><%= link_to item.title , project_path(item) %></td>
      <td><%= item.text %></td>
      <td>
        <% if ! item.last_build.nil? %>
            <%= link_to "ID: #{item.last_build.id}", [item, item.last_build] %> - <%= item.last_build[:state] %> <%= item.last_build[:updated_at].strftime('%B %d, %Y at %H:%M') %>
        <% else %>
            ---
        <% end %>
      </td>
      <td>
        <% if ! item.last_build.nil? and ! item.last_build.distribution_name.nil? %>
             <%= link_to "#{item.last_build.distribution_name}", url_for([item,item.last_build]) + '/artefacts/' + item.last_build.distribution_name  %>
        <% else %>
            ---
        <% end %>
      </td>
      <td>
            <%= Build.where("project_id = ?",item.id).count %> /
            <%= Build.where("project_id = ? and state = ?",item.id, 'succeeded' ).count %>
      </td>  
      <td>
        <%= link_to 'Show', project_path(item) %> | <%= link_to 'Edit', edit_project_path(item) %> |<%= link_to 'Run New Build', [item, item.builds.build], method: :post %> | <%= link_to 'Delete', project_path(item), method: :delete, data: { confirm:    "You are about to delete project # #{item[:id]}. Are you shure ?" }  %> | <%= link_to 'Acitivity Log', activity_project_path(item), :title => "show project's activity log"  %>
      </td>
    </tr>
  <% end %>
</table>

<hr>

jessy/app/views/projects/new.html.erb
<h1>New project</h1>
<%= render 'form' %>

jessy/app/views/projects/show.html.erb
<pre>
  <strong>Title:</strong> <%= @project.title %>
  <strong>Description:</strong> <%= @project.text %>
        <% if @project.has_distribution_source? == true %>
  <strong>Application Main Component:</strong> <%= @project.distribution_indexed_url %>
        <% else %>
  <strong>Application Source:</strong> not set
        <% end %>
</pre>

<%- if @project.last_build and  @project.last_build.has_components? %>
<pre>
  <strong>Latest Build Summary:</strong>
<% @project.last_build.components.each do |item| %>
    <%= link_to item.indexed_url , item.url, title: "SCM TYPE: #{item.scm_type} ID:#{item.id}" %> | rev: <%= item[:revision] %>
<% end %>
</pre>
<%- end %>

[ 

 <%= link_to 'Edit Project', edit_project_path(@project) %> | 
 <%= link_to 'Run New Build', url_for([@project, :builds]), method: :post  %> |
 <%= link_to 'Delete Project', project_path(@project), method: :delete, data: { confirm:    "You are about to delete project # #{@project[:id]}. Are you shure ?" }  %>
<%- if @project.has_last_successfull_build? == true %>
 | <%= link_to 'Last Successfull Build', project_path(@project) + '/last_successfull_build'  %>
<% end %>
 | <%= link_to 'Activity Log', activity_project_path(@project), :title => "show project's activity"  %>

]


<%- unless @project.builds.empty? %>
<% i = 0 %>
<br><br><br>
<pre>
  <strong>Builds History.</strong>
</pre>

    <table class="table-bordered table-striped table">
      <tr>
        <th>NN</th>
        <th>ID</th>
        <th>Status</th>
        <th>Compile ID</th>
        <th>Pinto Log</th>
        <th>Compile Log</th>
        <th>Parent Build</th>
        <th>Updated</th>
        <th>Artefacts</th>
        <th>Locked?</th>
        <th>Released?</th>
        <th>Annotation</th>
        <th>Actions</th>
      </tr>
    <% @project.builds.reverse.each do |item| %>
        <% if item[:state] == 'succeeded'  %>
        <% tr_class = 'success' %>
        <% elsif item[:state] == 'failed' %>
        <% tr_class = 'error' %>
        <% else %>
        <% tr_class = 'info' %>
        <% end %>

        <tr>
            <% i+=1 %>
            <td>
                <%= i %>
            </td>
            <td>
                <%= item.id %>
            </td>
            <td>
                <%= item[:state] %>
            </td>
            <td>
                <%= item.jc_id || '---' %>
            </td>
            <td>
                <%= link_to "view", [@project, item] %>
            </td>
            <td>
                <% if item.jc_id %>
                    <%= link_to "view", jc_log_project_build_path(@project,item), :title => 'show compile log from jc service' %>
                <% else %>
                    ---
                <% end %>
            </td>
            <td>
                <%= item[:parent_id] || '---' %>
            </td>
            <td>
                <%= item[:updated_at].strftime('%B %d, %Y at %H:%M') %>
            </td>
            <td>
            <% if item.distribution_name.nil? == false %>
                <%= link_to "#{item.distribution_name}", url_for([@project,item]) + '/artefacts/' + item.distribution_name  %>
            <% else %>
                ---
            <% end %>
            </td>
            <td>
                <% if item.locked?  %>
                    <b><font color='black'>yes</font></b>
                <% else %>
                    no
                <% end %>
            </td>
            <td>
                <% if item.released?  %>
                    <b><font color='green'>yes</font></b>
                <% else %>
                    no
                <% end %>
            </td>
            <td>
                <% if ! item.comment.nil?  %>
                    <i><%= item.short_comment %></i>
                <% else %>
                    ---
                <% end %>
            </td>
            <td>
                <% unless item.released?  %>
                    <%= link_to "delete", [@project, item], :method => :delete, :title => 'permanently delete this build' %> |
                <% end %>
                <% if item.locked? and ! item.released? %>
                    <%= link_to "unlock", [:unlock, @project, item ], :method => :post , :title => 'keep this build forever' %> |
                <% elsif ! item.released?  %>
                    <%= link_to "lock", [:lock, @project, item], :method => :post , :title => 'keep this build forever'  %>  |
                <% end %>
                <% unless item.released?  %>
                    <%= link_to "release", [ :release, @project, item ], :method => :post , :title => 'mark this build as released' %> |
                <% end %> 
                <%= link_to "annotate", edit_project_build_path(@project, item), :title => 'add description for this build'  %> |
                <%= link_to "configuration", configuration_project_build_path(@project, item), :title => 'show build configuration'  %> |
                <%= link_to 'distributions list', list_project_build_path(@project, item), :title => 'list of distribution archives' %> |
                <%= link_to "changes", changes_project_build_path(@project, item),  :title => 'last changes applied to build' %> |
                <%= link_to 'revert', revert_project_build_path(@project,item), :method => :post, :title => 'revert project to this build' %>
            </td>
            </tr>
    <% end %>
<% end %>