jessy/config/routes.rb
Ui::Application.routes.draw do

  devise_for :users

    root 'projects#index'

    resources :welcome 

    resource :activity do
    end

    resource :settings do
    end

    resources :projects do

        member do
            get 'last_successfull_build'
            get 'activity'
        end

        resources :builds do

            member do
                get     'changes'
                get     'list'
                get     'full_log'
                get     'jc_log'
                get     'cpanm_log'
                get     'configuration'
                get     'artefacts/*archive/', to: 'builds#download'
                post    'lock'
                post    'unlock'
                post    'release'
                post    'revert'
            end

            resources :shanpshots do
            end
    
        end
        
        resources :sources do
            member do
                post 'on'
                post 'off'
                post 'app'
            end
        end
    end
     

end

jessy/app/models/build.rb
require 'fileutils'
class Build < ActiveRecord::Base

    belongs_to :project

    has_many :snapshots, :dependent => :destroy

#    validates :comment, presence: true , length: { minimum: 10 }

    def log_path
        "#{local_path}/log.txt"
    end

    def touch_log_file
        FileUtils.touch log_path
    end

    def logger
        if @logger 
            @logger
        else
            f = File.open(log_path, 'a')
            f.sync = true
            @logger =  Logger.new f
        end
    end

    def log level, line
        if line.is_a? Array 
            line.split("\n").each do |l|
                logger.send( level, l.chomp )
            end
        elsif line.is_a? String
            logger.send( level, line.chomp )
        else
            raise "usage log(line) where line is_a Array|String"
        end
    end


    def local_path
        "#{ENV['HOME']}/.jessy/builds/#{id}"
    end

    def components 
       snapshots.order( id: :asc )
    end

    def main_component  
       snapshots.where(' is_distribution_url = ? ', true ).first
    end

    def component_by_indexed_url indexed_url
       snapshots.where(' indexed_url = ? ', indexed_url ).first
    end

    def has_main_component?
        ! main_component.nil?
    end

    def has_components?
        ! snapshots.empty?
    end

    def has_logs?
        File.readlines(log_path).size > 0
    end


    def recent_log_entries
         a = File.readlines(log_path)
         s = a.size
         if s >= recent_log_entries_number
            a[-recent_log_entries_number .. -1]
         else
            a
         end   
    end

    def all_log_entries
        File.readlines(log_path)
    end

    def recent_log_entries_number
        100
    end

    def short_comment
        "#{comment[0..70]} ... "
    end

    def ancestor
        Build.limit(1).order( id: :desc ).where(' project_id = ? AND id < ? AND has_stack = ?  AND has_install_base = ? ', project_id, id, true, true ).first
    end

    def precedent
         Build.limit(1).order( id: :desc ).where(' project_id = ? AND id < ? ', project_id, id ).first
    end

    def has_parent?
        parent_id
    end

    def has_ancestor?
        ancestor.nil? == false
    end

    def locked?
        locked == true
    end

    def stackable?
        has_stack == true
    end

    def released?
        released == true
    end

    def succeeded?
        state == 'succeeded'
    end

    def has_install_base?
        has_install_base
    end

end

jessy/app/controllers/builds_controller.rb
require 'fileutils'
require 'diff/lcs'
require 'diff/lcs/htmldiff'
require 'open3'

class BuildsController < ApplicationController

    skip_before_filter :authenticate_user!, :only => [ :destroy, :download, :revert, :create ]

    def create

        @project = Project.find(params[:project_id])

        @build = @project.builds.create!
        
        FileUtils.mkdir_p @build.local_path
        @build.touch_log_file

        make_snapshot @project, @build

        if current_user.nil?
            comm = 'anonimous'
        else
            comm = current_user.username
        end

        @project.history.create!( { :commiter => comm, :action => "run build ID: #{@build.id}" })

        Delayed::Job.enqueue(BuildAsync.new(@project, @build, Distribution, Setting.take, { :root_url => root_url  } ),0, Time.zone.now ) 
        message = "build ID: #{@build.id} for project ID: #{params[:project_id]} has been successfully scheduled at #{Time.zone.now}"
        flash[:notice] = message

        if request.env["HTTP_REFERER"].nil?
            render  :text => "#{message}\n"
        else
            redirect_to @project 
        end
    
    end

    def revert

        @project = Project.find(params[:project_id])
        parent_build = Build.find(params[:id])
        parent_project =  Project.find(parent_build.project_id)


        if current_user.nil?
            comm = 'anonimous'
        else
            comm = current_user.username
        end

        @project.history.create!  :commiter => comm, :action => "revert project to build ID: #{parent_build.id}" 

        if parent_build.succeeded?

            @build = @project.builds.create!({ :parent_id => parent_build.id })

            FileUtils.mkdir_p @build.local_path
            @build.touch_log_file

            @build.log :info, "create build ID:#{@build.id}"

            # remove all project's sources 
            @project.sources.each  do |s|
                indexed_url =  s._indexed_url
                s.destroy!
                @build.log :debug, "remove #{indexed_url}"
            end

            # creates new project's sources based on snapshot for parent build
            # creates new build's shanpshot as copy of parent's build one
            i = 0
            parent_build.components.each do |cmp|
                i += 1    
                new_source = @project.sources.create({ :scm_type => cmp[:scm_type] , :url => cmp.url , :sn => i*10, :git_tag => cmp[:git_tag], :git_branch => cmp[:git_branch], :git_folder => cmp[:git_folder]  })
                new_source.save!
                @build.log :debug, "add #{cmp.indexed_url} to project ID:#{@project.id}"
                if cmp.main?
                    @project.update!({ :distribution_source_id => new_source.id })
                    @build.log :debug, "mark source ID: #{new_source.id}; indexed_url: #{cmp.indexed_url} as an main application component source for project ID: #{@project.id}"
                end
                cmp_new = @build.snapshots.create!({ 
                    :indexed_url => cmp[:indexed_url], 
                    :revision => cmp[:revision], 
                    :scm_type => cmp[:scm_type], 
                    :schema => cmp[:schema],
                    :is_distribution_url => cmp[:is_distribution_url],
                    :git_branch => cmp[:git_branch], 
                    :git_tag => cmp[:git_tag], 
                    :git_folder => cmp[:git_folder]
                })
                cmp_new.save!
            end

            # re-read project data from DB
            @project.reload

            settings = Setting.take
            copy_stack_cmd = "pinto --root=#{settings.pinto_repo_root} copy #{parent_project.id}-#{parent_build.id} #{@project.id}-#{@build.id} --no-color"

            @build.log :debug, "running command: #{copy_stack_cmd}"
            execute_command copy_stack_cmd
            @build.log :debug, "command: #{copy_stack_cmd} succeeded"

            @build.update  :has_stack => true, :state => 'succeeded', :distribution_name => parent_build[:distribution_name]
            @build.save!

            if params[:no_copy_install_base]
                @build.log :debug, "do not copy install base due to param[:no_copy_install_base] is set to <#{params[:no_copy_install_base]}>"
                flash[:notice] = "build ID: #{@build.id} for project ID: #{params[:project_id]} has been successfully reverted; parent build ID: #{@build.parent_id}"
            else
                @build.log :debug, "create jc build"
    
                resp = @project.jcc.request :post, '/builds',  'build[key_id]' => "#{@build.id}" 
                jc_id = resp.headers[:build_id]
                @build.log :debug, "create jc build ok. js_id:#{jc_id}"

                @build.update!  :jc_id => jc_id
                @build.save!
    
                @build.log :debug, "copy ancestor build via jc server, ancestor build_id: #{parent_build.id}"
                resp = @project.jcc.request :post, "/builds/#{jc_id}/copy", 'jc_id' => "#{parent_build.jc_id}"
                @build.log :debug, "copy jc build ok"
    
                @build.update!  :has_install_base => true 
                @build.save!
    
                @build.log :info,  "successfully reverted project to build ID: #{parent_build.id}; new build ID: #{@build.id}"
                message = "build ID: #{@build.id} for project ID: #{params[:project_id]} has been successfully reverted; parent build ID: #{@build.parent_id}"    
                flash[:notice] = message
            end            
        else
            message =  "cannot revert project to unsucceded build; parent build ID:#{parent_build.id}; state:#{parent_build.state}"
            flash[:alert] = message
        end

        if request.env["HTTP_REFERER"].nil?
            render  :text => "#{message}\n"
        else
            redirect_to @project
        end

    end

    def show
        @project = Project.find(params[:project_id])
        @build = Build.find(params[:id])
        @log_entries = @build.recent_log_entries
    end

    def configuration
        @project = Project.find(params[:project_id])
        @build = Build.find(params[:id])
        @data = @build.snapshots
    end

    def edit
        @project = Project.find(params[:project_id])
        @build = Build.find(params[:id])
    end

    def update 
        @project = Project.find(params[:project_id])
        @build = Build.find(params[:id])
        
        if @build.update(builds_params)
            @project.history.create!( { :commiter => current_user.username, :action => "annotate build ID: #{@build.id}" })
            flash[:notice] = "build ID:#{@build.id} has been successfully annotated"
            redirect_to @project
        else
            flash[:alert] = "error has been occured when annotating build ID:#{@build.id}"
            render 'edit'
        end
    end

    def full_log
        @project = Project.find(params[:project_id])
        @build = Build.find(params[:id])
        @log_entries = @build.all_log_entries
    end

    def list
        @project = Project.find(params[:project_id])
        @build = Build.find(params[:id])
        @list = `pinto --root=#{Setting.take.pinto_repo_root} list -s #{@project.id}-#{@build.id} --no-color --format '%a/%f' | sort | uniq `.split "\n"
    end

    def changes

        @project = Project.find(params[:project_id])
        @build = Build.find(params[:id])


        if ! params[:build].nil? and  ! params[:build][:id].nil?
            @precendent =  Build.find(params[:build][:id]) 
        else
            @precendent =  @build.precedent 
        end

        if @precendent.nil?
            flash[:alert] = "cannot find precendent for build ID:#{@build.id}"
            redirect_to project_path(@project,@build)
        else

            @pinto_diff = execute_command("pinto --root=#{Setting.take.pinto_repo_root} diff #{@project.id}-#{@build.id} #{@project.id}-#{@precendent.id}  --no-color", false)
    
            Diff::LCS::HTMLDiff.can_expand_tabs = false
    
            s = StringIO.new
            
            if  @precendent.snapshots.empty?
                @snapshot_diff = "<pre>insufficient data for build ID: #{@precendent.id}</pre>"
            elsif  @build.snapshots.empty?
                @snapshot_diff = "<pre>insufficient data for build ID: #{@build.id}</pre>"
            else
                Diff::LCS::HTMLDiff.new( 
                    @precendent.components.map  { |cmp| ( cmp.main? ? '(app) ' : '' ) +  (cmp[:indexed_url] || 'NULL') }.sort, 
                    @build.components.map       {|cmp|  ( cmp.main? ? '(app) ' : '' ) +  (cmp[:indexed_url] || 'NULL') }.sort , 
                    :title => "diff #{@build.id} #{@precendent.id}" ,
                    :output => s
                ).run
    
                @snapshot_diff = s.string
                @snapshot_diff.sub!(/<html>.*<body>/m) { "" } 
                @snapshot_diff.gsub! '<h1>', '<strong>'
                @snapshot_diff.gsub! '</h1>', '</strong>'
                @snapshot_diff.sub! '</html>', ''
                @snapshot_diff.sub! '</body>', ''
    
            end

            @history = History.order( id: :desc ).where('project_id = ? AND created_at >= ?  AND created_at <= ? ', @project[:id], @precendent[:created_at], @build[:created_at] );

        end

    end

    def destroy
        @project = Project.find(params[:project_id])
        build = Build.find(params[:id])

        if current_user.nil?
            comm = 'anonimous'
        else
            comm = current_user.username
        end


        `pinto --root=#{Setting.take.pinto_repo_root} kill #{@project.id}-#{build.id}`

        jc_id = nil
        if build.locked? or  build.released?
            message = "cannot delete locked  or released build! ID:#{params[:id]}"
            flash[:alert] = message
        else
            FileUtils.rm_rf build.local_path
            jc_id = build.jc_id

jessy/app/helpers/builds_helper.rb
module BuildsHelper
end

jessy/app/views/builds/_form.html.erb
<%= form_for [@project, @build] do |f| %>
  <% if @build.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@build.errors.count, "error") %> prohibited
      this build from being annotate:</h2>
    <ul>
    <% @build.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment, :size => "100x10" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>

jessy/app/views/builds/changes.html.erb
<%= link_to 'Back To Project', project_path(@project) %> | 
<strong>Changes</strong> |
<%= link_to 'Full Log', full_log_project_build_path(@project,@build), :title => 'full log' %> |
<%= link_to 'Distributions List', list_project_build_path(@project,@build), :title => 'list of distribution archives' %> |
<%= link_to 'Configuration', configuration_project_build_path(@project,@build), :title => 'show build configuration' %> |
<%= link_to 'Revert', revert_project_build_path(@project,@build), :method => :post, :title => 'revert project to this build' %>
<% unless @build.released?  %>
| <%= link_to "Delete", [@project, @build], :method => :delete, :title => 'permanently delete this build' %>
<% end %>

<pre>
  <strong>Project Title:</strong> <%= @project.title %>
  <strong>Project ID:</strong> <%= @project.id %>
  <strong>Build ID:</strong> <%= @build.id %>
  <strong>State:</strong> <%= @build.state %>
  <strong>List of Changes:</strong> Between Build ID:<%= @build.id %> And Build ID:<%= @precendent.id %>
</pre>



<table class="table-bordered table-striped table">
  <tr>
    <th>Distribution Difference</th>
    <th>Source Changes / Change Log</th>
    <th>Choose other builds</th>
  </tr>
  <tr>
    <td valign=top>
<pre>
<% @pinto_diff.each do |l| %>
  <%= l  %>
<% end %>
</pre>
   </td>
    <td valign=top>
  <%= raw(@snapshot_diff) %>
  <strong>Change Log</strong>
  <table class="table-bordered table-striped table">
  <tr>
    <th>Time</th>
    <th>Commiter</th>
    <th>Action</th>
  </tr>
  <% @history.each do |l| %>
  <tr>
    <td>
        <%= l[:created_at].strftime('%B %d, %Y at %H:%M')  %>
    </td>
    <td>
        <%= l[:commiter].nil? ? 'anonimous' : begin c = Resolv.new.getname(l[:commiter]) rescue l[:commiter] else c end   %>
    </td>
    <td>
        <%= l[:action] %>
    </td>
  </tr>  
  <% end %>
  </table>
   </td>
    <td>
        <%= form_for([@project, @build], url: { action: "changes" }, method: :get  ) do |f| %>
             <%= f.select :id, options_for_select(@project.builds.reverse.map {|b| b.released? ? [ "[R] #{b.id}", b.id ] : [b.id] }) %>
             <%= f.submit "Compare" %> 
       <% end %>
    </td>
 </tr>
</table>

[

 <%= link_to 'Back To Project', project_path(@project) %>

]

jessy/app/views/builds/configuration.html.erb
  <%= link_to 'Back To Project', project_path(@project) %> |
  <strong>Configuration</strong> |
    <%= link_to 'Full Log', full_log_project_build_path(@project,@build), :title => 'full log' %> |
    <%= link_to 'Distributions List', list_project_build_path(@project,@build), :title => 'list of distributions archives' %> |
    <%= link_to 'Changes', changes_project_build_path(@project,@build), :title => 'changes for this build' %> |
    <%= link_to 'Revert', revert_project_build_path(@project,@build), :method => :post, :title => 'revert project to this build' %>
    <% unless @build.released?  %>
    | <%= link_to "Delete", [@project, @build], :method => :delete, :title => 'permanently delete this build' %>
    <% end %>

<pre>
  <strong>Project Title:</strong> <%= @project.title %>
  <strong>Project ID:</strong> <%= @project.id %>
  <strong>Build ID:</strong> <%= @build.id %>
  <strong>State:</strong> <%= @build.state %>
</pre>

<% if ! @build.comment.nil?  %>
  <strong>Annotation:</strong> 
<pre>
<%= @build.comment %>
</pre>
<% end %>


    <table class="table-bordered table-striped table">
      <tr>
        <th>Component</th>
        <th>URL</th>
        <th>Schema</th>
        <th>SCM Type</th>
        <th>Git Branch</th>
        <th>Git Folder</th>
        <th>Is Main ?</th>
        <th>revision</th>
        <th>ID</th>
      </tr>
    <% @data.each do |item| %>
    <tr>
        <td><%= item[:indexed_url] %></td>
        <td><%= item.url %></td>
        <td><%= item[:schema] %></td>
        <td><%= item[:scm_type] %></td>
        <td><%= item[:scm_type] == 'git' ? item.git_br_or_tag : '---' %></td>
        <td><%= item[:git_folder] || '---' %></td>
        <td><%= item[:is_distribution_url]? 'yes' : 'no'  %></td>
        <td><%= item[:revision] || '---' %></td>
        <td><%= item[:id] %></td>
    </tr>
    <% end %>
    </table>
[ 

 <%= link_to 'Back To Project', project_path(@project) %> 

]

jessy/app/views/builds/cpanm_log.html.erb
<%= link_to 'Back To Project', project_path(@project) %> |
<strong>Cpanm Log </strong> |
    <%= link_to "Recent Log", project_build_path(@project,@build), :title => "Last Entries #{@build.recent_log_entries_number}" %> |
    <%= link_to 'Full Log', full_log_project_build_path(@project,@build), :title => 'full log' %> |
    <%= link_to "Compile Log", jc_log_project_build_path(@project,@build), :title => 'Show comoile log from jc service' %> |
    <%= link_to 'Distributions List', list_project_build_path(@project,@build), :title => 'list of distributions archives' %> |
    <%= link_to 'Configuration', configuration_project_build_path(@project,@build), :title => 'show build configuration' %> |
    <%= link_to 'Changes', changes_project_build_path(@project,@build), :title => 'changes for this build' %>
    <% unless @build.released?  %>
    | <%= link_to "Delete", [@project, @build], :method => :delete, :title => 'permanently delete this build' %>
    <% end %>

<pre>
  <strong>Project Title:</strong> <%= @project.title %>
  <strong>Project ID:</strong> <%= @project.id %>
  <strong>Build ID:</strong> <%= @build.id %>
  <strong>Compile ID:</strong> <%= @build.jc_id %>
  <strong>State:</strong> <%= @build.state %>
</pre>


<pre>
    <%= @data %>
</pre>

[

 <%= link_to 'Back To Project', project_path(@project) %>

]

jessy/app/views/builds/create.html.erb
<h2><%= @message %></h2>
<%= link_to "Back to Project", edit_project_path(@project) %>

jessy/app/views/builds/edit.html.erb
<h2>Annotate build ID: <%= @build.id %> / project <%= link_to "ID:#{@project[:id]}",  project_path(@project[:id]) %></h2>

<%= render 'form' %>

jessy/app/views/builds/full_log.html.erb
<%= link_to 'Back To Project', project_path(@project) %> |
<strong>Full Log </strong> |  
    <%= link_to "Recent Log", project_build_path(@project,@build), :title => "Last Entries #{@build.recent_log_entries_number}" %> |
    <% if @build.jc_id %>
    <%= link_to "Compile Log", jc_log_project_build_path(@project,@build), :title => 'Show comoile log from jc service' %> |
    <% end %>
    <%= link_to 'Distributions List', list_project_build_path(@project,@build), :title => 'list of distributions archives' %> |
    <%= link_to 'Configuration', configuration_project_build_path(@project,@build), :title => 'show build configuration' %> |
    <%= link_to 'Changes', changes_project_build_path(@project,@build), :title => 'changes for this build' %>
    <% unless @build.released?  %>
    | <%= link_to "Delete", [@project, @build], :method => :delete, :title => 'permanently delete this build' %>
    <% end %>

<pre>
  <strong>Project Title:</strong> <%= @project.title %>
  <strong>Project ID:</strong> <%= @project.id %>
  <strong>Build ID:</strong> <%= @build.id %>
  <strong>State:</strong> <%= @build.state %>
</pre>

<% if ! @build.comment.nil?  %>
  <strong>Annotation:</strong>
<pre>
<%= @build.comment %>
</pre>
<% end %>

<pre>
<% @log_entries.each do |line| %>
<%= line.chomp  %>
<% end %>
</pre>

[ 

 <%= link_to 'Back To Project', project_path(@project) %> 

]

jessy/app/views/builds/jc_log.html.erb
<%= link_to 'Back To Project', project_path(@project) %> |
<strong>Compile Log </strong> |
    <%= link_to "Recent Log", project_build_path(@project,@build), :title => "Last Entries #{@build.recent_log_entries_number}" %> |
    <%= link_to 'Full Log', full_log_project_build_path(@project,@build), :title => 'full log' %> |
    <%= link_to 'Distributions List', list_project_build_path(@project,@build), :title => 'list of distributions archives' %> |
    <%= link_to 'Configuration', configuration_project_build_path(@project,@build), :title => 'show build configuration' %> |
    <%= link_to 'Changes', changes_project_build_path(@project,@build), :title => 'changes for this build' %>
    <% unless @build.released?  %>
    | <%= link_to "Delete", [@project, @build], :method => :delete, :title => 'permanently delete this build' %>
    <% end %>

<pre>
  <strong>Project Title:</strong> <%= @project.title %>
  <strong>Project ID:</strong> <%= @project.id %>
  <strong>Build ID:</strong> <%= @build.id %>
  <strong>Compile ID:</strong> <%= @build.jc_id %>
  <strong>State:</strong> <%= @build.state %>
</pre>


<pre>
<% @data.split("\n").each do |l| %>
    <% if ( m  = /See .*\/(.*?)\/build\.log for details/.match l ) %>
    <%= l %> <%= link_to "[#{m[1]}]", cpanm_log_project_build_path( @project,@build, :cpanm_id => m[1] ) %>
    <% else  %>
    <%= l %>
    <% end %>
<% end %>
</pre>

[

 <%= link_to 'Back To Project', project_path(@project) %>

]

jessy/app/views/builds/list.html.erb
<%= link_to 'Back To Project', project_path(@project) %> | <strong>Distributions List</strong> |
<%= link_to 'Full Log', full_log_project_build_path(@project,@build), :title => 'full log' %> |
<%= link_to 'Configuration', configuration_project_build_path(@project,@build), :title => 'show build configuration' %> |
<%= link_to 'Revert', revert_project_build_path(@project,@build), :method => :post, :title => 'revert project to this build' %>
<% unless @build.released?  %>
| <%= link_to "Delete", [@project, @build], :method => :delete, :title => 'permanently delete this build' %>
<% end %>

<pre>
  <strong>Project Title:</strong> <%= @project.title %>
  <strong>Project ID:</strong> <%= @project.id %>
  <strong>Build ID:</strong> <%= @build.id %>
  <strong>State:</strong> <%= @build.state %>
</pre>

<pre>
<%- i = 0 %>	
<% @list.each do |d| %>
  <%= d  %>
<% end %>
</pre>

[ 

 <%= link_to 'Back To Project', project_path(@project) %> 

]

jessy/app/views/builds/show.html.erb
  <%= link_to 'Back To Project', project_path(@project) %> |
  <strong>Recent Log</strong> |
    <%= link_to 'Full Log', full_log_project_build_path(@project,@build), :title => 'full log' %> | 
    <% if @build.jc_id %>
    <%= link_to "Compile Log", jc_log_project_build_path(@project,@build), :title => 'show compile log from jc service' %> |
    <% end %>
    <%= link_to 'Distributions List', list_project_build_path(@project,@build), :title => 'list of distribution archives' %> |
    <%= link_to 'Configuration', configuration_project_build_path(@project,@build), :title => 'show build configuration' %> |
    <%= link_to 'Changes', changes_project_build_path(@project,@build), :title => 'changes for this build' %> |
    <%= link_to 'Revert', revert_project_build_path(@project,@build), :method => :post, :title => 'revert project to this build' %>
    <% unless @build.released?  %>
    | <%= link_to "Delete", [@project, @build], :method => :delete, :title => 'permanently delete this build' %>
    <% end %>

<pre>
  <strong>Project Title:</strong> <%= @project.title %>
  <strong>Project ID:</strong> <%= @project.id %>
  <strong>Build ID:</strong> <%= @build.id %>
  <strong>State:</strong> <%= @build.state %>
</pre>

<% if ! @build.comment.nil?  %>
  <strong>Annotation:</strong> 
<pre>
<%= @build.comment %>
</pre>
<% end %>


<pre>
<% @log_entries.each do |line| %>
<%= line.chomp  %>
<% end %>
</pre>

[ 

 <%= link_to 'Back To Project', project_path(@project) %> 

]