jessy/config/routes.rb
Ui::Application.routes.draw do

  devise_for :users

    root 'projects#index'

    resources :welcome 

    resource :activity do
    end

    resource :settings do
    end

    resources :projects do

        member do
            get 'last_successfull_build'
            get 'activity'
        end

        resources :builds do

            member do
                get     'changes'
                get     'list'
                get     'full_log'
                get     'jc_log'
                get     'cpanm_log'
                get     'configuration'
                get     'artefacts/*archive/', to: 'builds#download'
                post    'lock'
                post    'unlock'
                post    'release'
                post    'revert'
            end

            resources :shanpshots do
            end
    
        end
        
        resources :sources do
            member do
                post 'on'
                post 'off'
                post 'app'
            end
        end
    end
     

end

jessy/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

jessy/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <%= link_to 'Projects List', projects_path, class: 'navbar-brand' %>
      <%= link_to 'New Project', new_project_path, class: 'navbar-brand' %>
      <%= link_to 'Configuration', edit_settings_path, class: 'navbar-brand', title: "click to edit configuration settings" %>
      <%= link_to 'Activity Log', activity_path, class: 'navbar-brand', title: "Show activity log" %>
      <%= link_to 'About', welcome_index_path , class: 'navbar-brand' %>
      <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete , class: 'navbar-brand') %>
      <% else %>
      <%= link_to('Login', new_user_session_path , class: 'navbar-brand') %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

jessy/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

jessy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jessy" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Jessy" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>